-- =============================================================================
-- DGPULSE FOR DV360: DEMO DATASET GENERATOR
-- Populates all 8 Looker Studio data sources with comprehensive synthetic data
-- showcasing all pacing statuses, audit alerts, creative varieties, and audiences.
-- =============================================================================

-- 1. CAMPAIGN PERFORMANCE (final_campaign_performance)
CREATE OR REPLACE TABLE `__PROJECT_ID__.__DATASET_ID__.final_campaign_performance` AS
SELECT * FROM UNNEST([
  STRUCT(
    DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY) AS date,
    'cmp_1001' AS campaign_id,
    'Acme Global - Demand Gen Q3 Brand Launch' AS campaign_name,
    'ENTITY_STATUS_ACTIVE' AS entity_status,
    'adv_8801' AS advertiser_id,
    'adv_8801' AS account_id,
    'Acme Retail Global' AS account_name,
    'USD' AS currency_code,
    'NO' AS is_limited_by_budget,
    3 AS line_item_count,
    'YES' AS data_manager_crm_connected,
    'YES' AS data_manager_ga_connected,
    '🟢 READY' AS gtg_status,
    'WEB_TAG_TYPE_DYNAMIC' AS web_tag_type,
    'PASSED' AS data_strength_status,
    'partner_9901' AS partner_id,
    450000 AS impressions,
    18200 AS clicks,
    14500.0 AS cost,
    14500.0 AS cost_usd,
    0.0404 AS ctr,
    0.7967 AS cpc,
    0.7967 AS cpc_usd,
    32.22 AS cpm,
    32.22 AS cpm_usd,
    315000 AS active_view_viewable_impressions,
    360000 AS active_view_measurable_impressions,
    450000 AS active_view_eligible_impressions,
    0.875 AS viewability_rate,
    0.800 AS measurable_rate,
    120000 AS trueview_views,
    0.2667 AS vtr,
    140000 AS video_plays,
    105000 AS video_first_quartile_completes,
    70000 AS video_midpoints,
    49000 AS video_third_quartile_completes,
    42000 AS video_completions,
    0.3000 AS video_completion_rate,
    980.0 AS conversions,
    620.0 AS post_click_conversions,
    360.0 AS post_view_conversions,
    31000.0 AS post_click_revenue,
    12600.0 AS post_view_revenue,
    0.0341 AS post_click_conv_rate,
    96.5 AS io_goal_pacing_pct,
    2.1 AS lost_is_budget,
    4.3 AS lost_is_rank
  ),
  STRUCT(
    DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY) AS date,
    'cmp_1002' AS campaign_id,
    'OmniTech - DG Mid-Funnel Considerations' AS campaign_name,
    'ENTITY_STATUS_ACTIVE' AS entity_status,
    'adv_8802' AS advertiser_id,
    'adv_8802' AS account_id,
    'OmniTech Solutions' AS account_name,
    'EUR' AS currency_code,
    'YES' AS is_limited_by_budget,
    2 AS line_item_count,
    'NO' AS data_manager_crm_connected,
    'YES' AS data_manager_ga_connected,
    '🔴 NEEDS_TAG_UPGRADE' AS gtg_status,
    'WEB_TAG_TYPE_IMAGE' AS web_tag_type,
    'PASSED' AS data_strength_status,
    'partner_9901' AS partner_id,
    210000 AS impressions,
    6300 AS clicks,
    7800.0 AS cost,
    8424.0 AS cost_usd,
    0.0300 AS ctr,
    1.2381 AS cpc,
    1.3371 AS cpc_usd,
    37.14 AS cpm,
    40.11 AS cpm_usd,
    136500 AS active_view_viewable_impressions,
    178500 AS active_view_measurable_impressions,
    210000 AS active_view_eligible_impressions,
    0.7647 AS viewability_rate,
    0.8500 AS measurable_rate,
    52500 AS trueview_views,
    0.2500 AS vtr,
    65000 AS video_plays,
    45500 AS video_first_quartile_completes,
    32500 AS video_midpoints,
    22750 AS video_third_quartile_completes,
    19500 AS video_completions,
    0.3000 AS video_completion_rate,
    315.0 AS conversions,
    185.0 AS post_click_conversions,
    130.0 AS post_view_conversions,
    11100.0 AS post_click_revenue,
    5200.0 AS post_view_revenue,
    0.0294 AS post_click_conv_rate,
    78.2 AS io_goal_pacing_pct,
    14.8 AS lost_is_budget,
    8.2 AS lost_is_rank
  ),
  STRUCT(
    DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY) AS date,
    'cmp_1003' AS campaign_id,
    'Starlight - DG Direct Action Drive' AS campaign_name,
    'ENTITY_STATUS_ACTIVE' AS entity_status,
    'adv_8803' AS advertiser_id,
    'adv_8803' AS account_id,
    'Starlight Media' AS account_name,
    'GBP' AS currency_code,
    'NO' AS is_limited_by_budget,
    1 AS line_item_count,
    'NO' AS data_manager_crm_connected,
    'NO' AS data_manager_ga_connected,
    '⚪ NOT_CONFIGURED' AS gtg_status,
    'WEB_TAG_TYPE_NONE' AS web_tag_type,
    'NEEDS_ACTION' AS data_strength_status,
    'partner_9901' AS partner_id,
    95000 AS impressions,
    2850 AS clicks,
    3200.0 AS cost,
    4160.0 AS cost_usd,
    0.0300 AS ctr,
    1.1228 AS cpc,
    1.4596 AS cpc_usd,
    33.68 AS cpm,
    43.79 AS cpm_usd,
    66500 AS active_view_viewable_impressions,
    80750 AS active_view_measurable_impressions,
    95000 AS active_view_eligible_impressions,
    0.8235 AS viewability_rate,
    0.8500 AS measurable_rate,
    21000 AS trueview_views,
    0.2211 AS vtr,
    28000 AS video_plays,
    19600 AS video_first_quartile_completes,
    14000 AS video_midpoints,
    9800 AS video_third_quartile_completes,
    8400 AS video_completions,
    0.3000 AS video_completion_rate,
    120.0 AS conversions,
    75.0 AS post_click_conversions,
    45.0 AS post_view_conversions,
    3750.0 AS post_click_revenue,
    1800.0 AS post_view_revenue,
    0.0263 AS post_click_conv_rate,
    88.0 AS io_goal_pacing_pct,
    5.4 AS lost_is_budget,
    6.1 AS lost_is_rank
  )
]);

-- 2. LINE ITEMS PERFORMANCE (final_line_items_performance)
CREATE OR REPLACE TABLE `__PROJECT_ID__.__DATASET_ID__.final_line_items_performance` AS
SELECT * FROM UNNEST([
  STRUCT(
    DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY) AS date,
    'li_501' AS line_item_id,
    'Acme - DG Video Action - YouTube Shorts' AS line_item_name,
    'LINE_ITEM_TYPE_DEMAND_GEN' AS line_item_type,
    'YES' AS data_manager_crm_connected,
    'YES' AS data_manager_ga_connected,
    'PASSED' AS data_strength_status,
    'YES' AS ec_enabled,
    'YES' AS floodlight_optimization_enabled,
    'YES' AS auto_tagging_enabled,
    '🟢 READY' AS gtg_status,
    'WEB_TAG_TYPE_DYNAMIC' AS web_tag_type,
    'PASSED' AS activation_data_strength_status,
    'ENTITY_STATUS_ACTIVE' AS entity_status,
    'NO' AS is_limited_by_budget,
    'io_201' AS insertion_order_id,
    'Acme Q3 - On Track Flight' AS insertion_order_name,
    'PACING_TYPE_AHEAD' AS io_pacing_type,
    'PACING_PERIOD_FLIGHT' AS io_pacing_period,
    30000.0 AS io_budget_amount,
    'DEVICE_TYPE_MOBILE' AS device_type,
    'INVENTORY_SOURCE_YOUTUBE' AS inventory_source,
    'cmp_1001' AS campaign_id,
    'Acme Global - Demand Gen Q3 Brand Launch' AS campaign_name,
    'adv_8801' AS advertiser_id,
    'adv_8801' AS account_id,
    'Acme Retail Global' AS account_name,
    'USD' AS currency_code,
    'partner_9901' AS partner_id,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8801/c/cmp_1001/io/io_201/li/li_501/adgroups' AS line_item_link,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8801/c/cmp_1001/io/io_201/li/li_501/adgroups' AS dv360_url,
    250000 AS impressions,
    11200 AS clicks,
    8200.0 AS cost,
    8200.0 AS cost_usd,
    0.0448 AS ctr,
    0.7321 AS cpc,
    0.7321 AS cpc_usd,
    32.80 AS cpm,
    32.80 AS cpm_usd,
    185000 AS active_view_viewable_impressions,
    215000 AS active_view_measurable_impressions,
    250000 AS active_view_eligible_impressions,
    0.8605 AS viewability_rate,
    0.8600 AS measurable_rate,
    78000 AS trueview_views,
    0.3120 AS vtr,
    95000 AS video_plays,
    71250 AS video_first_quartile_completes,
    47500 AS video_midpoints,
    33250 AS video_third_quartile_completes,
    28500 AS video_completions,
    0.3000 AS video_completion_rate,
    620.0 AS conversions,
    410.0 AS post_click_conversions,
    210.0 AS post_view_conversions,
    21500.0 AS post_click_revenue,
    7800.0 AS post_view_revenue,
    0.0366 AS post_click_conv_rate,
    98.2 AS io_goal_pacing_pct,
    1.5 AS lost_is_budget,
    3.8 AS lost_is_rank
  ),
  STRUCT(
    DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY) AS date,
    'li_502' AS line_item_id,
    'Acme - DG Multi-Format Display & Discover' AS line_item_name,
    'LINE_ITEM_TYPE_DEMAND_GEN' AS line_item_type,
    'YES' AS data_manager_crm_connected,
    'YES' AS data_manager_ga_connected,
    'PASSED' AS data_strength_status,
    'YES' AS ec_enabled,
    'YES' AS floodlight_optimization_enabled,
    'YES' AS auto_tagging_enabled,
    '🟢 READY' AS gtg_status,
    'WEB_TAG_TYPE_DYNAMIC' AS web_tag_type,
    'PASSED' AS activation_data_strength_status,
    'ENTITY_STATUS_ACTIVE' AS entity_status,
    'NO' AS is_limited_by_budget,
    'io_201' AS insertion_order_id,
    'Acme Q3 - On Track Flight' AS insertion_order_name,
    'PACING_TYPE_AHEAD' AS io_pacing_type,
    'PACING_PERIOD_FLIGHT' AS io_pacing_period,
    30000.0 AS io_budget_amount,
    'DEVICE_TYPE_DESKTOP' AS device_type,
    'INVENTORY_SOURCE_GOOGLE_OWNED' AS inventory_source,
    'cmp_1001' AS campaign_id,
    'Acme Global - Demand Gen Q3 Brand Launch' AS campaign_name,
    'adv_8801' AS advertiser_id,
    'adv_8801' AS account_id,
    'Acme Retail Global' AS account_name,
    'USD' AS currency_code,
    'partner_9901' AS partner_id,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8801/c/cmp_1001/io/io_201/li/li_502/adgroups' AS line_item_link,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8801/c/cmp_1001/io/io_201/li/li_502/adgroups' AS dv360_url,
    200000 AS impressions,
    7000 AS clicks,
    6300.0 AS cost,
    6300.0 AS cost_usd,
    0.0350 AS ctr,
    0.9000 AS cpc,
    0.9000 AS cpc_usd,
    31.50 AS cpm,
    31.50 AS cpm_usd,
    130000 AS active_view_viewable_impressions,
    145000 AS active_view_measurable_impressions,
    200000 AS active_view_eligible_impressions,
    0.8966 AS viewability_rate,
    0.7250 AS measurable_rate,
    42000 AS trueview_views,
    0.2100 AS vtr,
    45000 AS video_plays,
    33750 AS video_first_quartile_completes,
    22500 AS video_midpoints,
    15750 AS video_third_quartile_completes,
    13500 AS video_completions,
    0.3000 AS video_completion_rate,
    360.0 AS conversions,
    210.0 AS post_click_conversions,
    150.0 AS post_view_conversions,
    9500.0 AS post_click_revenue,
    4800.0 AS post_view_revenue,
    0.0300 AS post_click_conv_rate,
    94.8 AS io_goal_pacing_pct,
    2.7 AS lost_is_budget,
    4.8 AS lost_is_rank
  ),
  STRUCT(
    DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY) AS date,
    'li_503' AS line_item_id,
    'OmniTech - DG In-Market Consideration' AS line_item_name,
    'LINE_ITEM_TYPE_DEMAND_GEN' AS line_item_type,
    'NO' AS data_manager_crm_connected,
    'YES' AS data_manager_ga_connected,
    'PASSED' AS data_strength_status,
    'NO' AS ec_enabled,
    'YES' AS floodlight_optimization_enabled,
    'YES' AS auto_tagging_enabled,
    '🔴 NEEDS_TAG_UPGRADE' AS gtg_status,
    'WEB_TAG_TYPE_IMAGE' AS web_tag_type,
    'NEEDS_ACTION' AS activation_data_strength_status,
    'ENTITY_STATUS_ACTIVE' AS entity_status,
    'YES' AS is_limited_by_budget,
    'io_202' AS insertion_order_id,
    'OmniTech - Underpacing Flight' AS insertion_order_name,
    'PACING_TYPE_EVEN' AS io_pacing_type,
    'PACING_PERIOD_FLIGHT' AS io_pacing_period,
    25000.0 AS io_budget_amount,
    'DEVICE_TYPE_MOBILE' AS device_type,
    'INVENTORY_SOURCE_YOUTUBE' AS inventory_source,
    'cmp_1002' AS campaign_id,
    'OmniTech - DG Mid-Funnel Considerations' AS campaign_name,
    'adv_8802' AS advertiser_id,
    'adv_8802' AS account_id,
    'OmniTech Solutions' AS account_name,
    'EUR' AS currency_code,
    'partner_9901' AS partner_id,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8802/c/cmp_1002/io/io_202/li/li_503/adgroups' AS line_item_link,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8802/c/cmp_1002/io/io_202/li/li_503/adgroups' AS dv360_url,
    210000 AS impressions,
    6300 AS clicks,
    7800.0 AS cost,
    8424.0 AS cost_usd,
    0.0300 AS ctr,
    1.2381 AS cpc,
    1.3371 AS cpc_usd,
    37.14 AS cpm,
    40.11 AS cpm_usd,
    136500 AS active_view_viewable_impressions,
    178500 AS active_view_measurable_impressions,
    210000 AS active_view_eligible_impressions,
    0.7647 AS viewability_rate,
    0.8500 AS measurable_rate,
    52500 AS trueview_views,
    0.2500 AS vtr,
    65000 AS video_plays,
    45500 AS video_first_quartile_completes,
    32500 AS video_midpoints,
    22750 AS video_third_quartile_completes,
    19500 AS video_completions,
    0.3000 AS video_completion_rate,
    315.0 AS conversions,
    185.0 AS post_click_conversions,
    130.0 AS post_view_conversions,
    11100.0 AS post_click_revenue,
    5200.0 AS post_view_revenue,
    0.0294 AS post_click_conv_rate,
    78.2 AS io_goal_pacing_pct,
    14.8 AS lost_is_budget,
    8.2 AS lost_is_rank
  ),
  STRUCT(
    DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY) AS date,
    'li_504' AS line_item_id,
    'Starlight - Action Prospecting' AS line_item_name,
    'LINE_ITEM_TYPE_DEMAND_GEN' AS line_item_type,
    'NO' AS data_manager_crm_connected,
    'NO' AS data_manager_ga_connected,
    'NEEDS_ACTION' AS data_strength_status,
    'NO' AS ec_enabled,
    'NO' AS floodlight_optimization_enabled,
    'NO' AS auto_tagging_enabled,
    '⚪ NOT_CONFIGURED' AS gtg_status,
    'WEB_TAG_TYPE_NONE' AS web_tag_type,
    'NEEDS_ACTION' AS activation_data_strength_status,
    'ENTITY_STATUS_ACTIVE' AS entity_status,
    'NO' AS is_limited_by_budget,
    'io_203' AS insertion_order_id,
    'Starlight - Overpacing Blitz' AS insertion_order_name,
    'PACING_TYPE_ASAP' AS io_pacing_type,
    'PACING_PERIOD_FLIGHT' AS io_pacing_period,
    10000.0 AS io_budget_amount,
    'DEVICE_TYPE_CONNECTED_TV' AS device_type,
    'INVENTORY_SOURCE_YOUTUBE' AS inventory_source,
    'cmp_1003' AS campaign_id,
    'Starlight - DG Direct Action Drive' AS campaign_name,
    'adv_8803' AS advertiser_id,
    'adv_8803' AS account_id,
    'Starlight Media' AS account_name,
    'GBP' AS currency_code,
    'partner_9901' AS partner_id,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8803/c/cmp_1003/io/io_203/li/li_504/adgroups' AS line_item_link,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8803/c/cmp_1003/io/io_203/li/li_504/adgroups' AS dv360_url,
    95000 AS impressions,
    2850 AS clicks,
    3200.0 AS cost,
    4160.0 AS cost_usd,
    0.0300 AS ctr,
    1.1228 AS cpc,
    1.4596 AS cpc_usd,
    33.68 AS cpm,
    43.79 AS cpm_usd,
    66500 AS active_view_viewable_impressions,
    80750 AS active_view_measurable_impressions,
    95000 AS active_view_eligible_impressions,
    0.8235 AS viewability_rate,
    0.8500 AS measurable_rate,
    21000 AS trueview_views,
    0.2211 AS vtr,
    28000 AS video_plays,
    19600 AS video_first_quartile_completes,
    14000 AS video_midpoints,
    9800 AS video_third_quartile_completes,
    8400 AS video_completions,
    0.3000 AS video_completion_rate,
    120.0 AS conversions,
    75.0 AS post_click_conversions,
    45.0 AS post_view_conversions,
    3750.0 AS post_click_revenue,
    1800.0 AS post_view_revenue,
    0.0263 AS post_click_conv_rate,
    88.0 AS io_goal_pacing_pct,
    5.4 AS lost_is_budget,
    6.1 AS lost_is_rank
  )
]);

-- 3. INSERTION ORDERS PERFORMANCE (final_insertion_orders_performance)
CREATE OR REPLACE TABLE `__PROJECT_ID__.__DATASET_ID__.final_insertion_orders_performance` AS
SELECT * FROM UNNEST([
  STRUCT(
    CURRENT_DATE() AS date,
    'io_201' AS insertion_order_id,
    'Acme Q3 - On Track Flight' AS insertion_order_name,
    'ENTITY_STATUS_ACTIVE' AS entity_status,
    'cmp_1001' AS campaign_id,
    'Acme Global - Demand Gen Q3 Brand Launch' AS campaign_name,
    'adv_8801' AS advertiser_id,
    'adv_8801' AS account_id,
    'Acme Retail Global' AS account_name,
    '🟢 READY' AS gtg_status,
    'WEB_TAG_TYPE_DYNAMIC' AS web_tag_type,
    'partner_9901' AS partner_id,
    'USD' AS currency_code,
    'PACING_TYPE_AHEAD' AS pacing_type,
    'PACING_PERIOD_FLIGHT' AS pacing_period,
    1500.0 AS daily_max_amount,
    'BUDGET_UNIT_CURRENCY' AS budget_unit,
    30000.0 AS budget_amount,
    DATE_SUB(CURRENT_DATE(), INTERVAL 15 DAY) AS start_date,
    DATE_ADD(CURRENT_DATE(), INTERVAL 15 DAY) AS end_date,
    15200.0 AS cumulative_spend,
    15200.0 AS cumulative_spend_usd,
    30 AS total_flight_days,
    15 AS elapsed_flight_days,
    15 AS remaining_flight_days,
    50.0 AS flight_elapsed_pct,
    50.67 AS budget_spent_pct,
    101.33 AS pacing_index_pct,
    1000.0 AS target_daily_budget,
    1013.33 AS current_daily_burn_rate,
    986.67 AS required_daily_burn_rate,
    30400.0 AS projected_flight_spend,
    0.0 AS budget_at_risk,
    0.0 AS budget_at_risk_usd,
    '🟢 ON_TRACK' AS pacing_status,
    450000 AS impressions,
    18200 AS clicks,
    14500.0 AS cost,
    14500.0 AS cost_usd,
    0.0404 AS ctr,
    0.7967 AS cpc,
    0.7967 AS cpc_usd,
    32.22 AS cpm,
    32.22 AS cpm_usd,
    315000 AS active_view_viewable_impressions,
    360000 AS active_view_measurable_impressions,
    450000 AS active_view_eligible_impressions,
    0.8750 AS viewability_rate,
    0.8000 AS measurable_rate,
    120000 AS trueview_views,
    0.2667 AS vtr,
    140000 AS video_plays,
    105000 AS video_first_quartile_completes,
    70000 AS video_midpoints,
    49000 AS video_third_quartile_completes,
    42000 AS video_completions,
    0.3000 AS video_completion_rate,
    980.0 AS conversions,
    620.0 AS post_click_conversions,
    360.0 AS post_view_conversions,
    31000.0 AS post_click_revenue,
    12600.0 AS post_view_revenue,
    0.0341 AS post_click_conv_rate,
    96.5 AS io_goal_pacing_pct,
    2.1 AS lost_is_budget,
    4.3 AS lost_is_rank
  ),
  STRUCT(
    CURRENT_DATE() AS date,
    'io_202' AS insertion_order_id,
    'OmniTech - Underpacing Flight' AS insertion_order_name,
    'ENTITY_STATUS_ACTIVE' AS entity_status,
    'cmp_1002' AS campaign_id,
    'OmniTech - DG Mid-Funnel Considerations' AS campaign_name,
    'adv_8802' AS advertiser_id,
    'adv_8802' AS account_id,
    'OmniTech Solutions' AS account_name,
    '🔴 NEEDS_TAG_UPGRADE' AS gtg_status,
    'WEB_TAG_TYPE_IMAGE' AS web_tag_type,
    'partner_9901' AS partner_id,
    'EUR' AS currency_code,
    'PACING_TYPE_EVEN' AS pacing_type,
    'PACING_PERIOD_FLIGHT' AS pacing_period,
    1200.0 AS daily_max_amount,
    'BUDGET_UNIT_CURRENCY' AS budget_unit,
    25000.0 AS budget_amount,
    DATE_SUB(CURRENT_DATE(), INTERVAL 20 DAY) AS start_date,
    DATE_ADD(CURRENT_DATE(), INTERVAL 10 DAY) AS end_date,
    7800.0 AS cumulative_spend,
    8424.0 AS cumulative_spend_usd,
    30 AS total_flight_days,
    20 AS elapsed_flight_days,
    10 AS remaining_flight_days,
    66.67 AS flight_elapsed_pct,
    31.20 AS budget_spent_pct,
    46.80 AS pacing_index_pct,
    833.33 AS target_daily_budget,
    390.00 AS current_daily_burn_rate,
    1720.00 AS required_daily_burn_rate,
    11700.0 AS projected_flight_spend,
    13300.0 AS budget_at_risk,
    14364.0 AS budget_at_risk_usd,
    '🟡 UNDERPACING' AS pacing_status,
    210000 AS impressions,
    6300 AS clicks,
    7800.0 AS cost,
    8424.0 AS cost_usd,
    0.0300 AS ctr,
    1.2381 AS cpc,
    1.3371 AS cpc_usd,
    37.14 AS cpm,
    40.11 AS cpm_usd,
    136500 AS active_view_viewable_impressions,
    178500 AS active_view_measurable_impressions,
    210000 AS active_view_eligible_impressions,
    0.7647 AS viewability_rate,
    0.8500 AS measurable_rate,
    52500 AS trueview_views,
    0.2500 AS vtr,
    65000 AS video_plays,
    45500 AS video_first_quartile_completes,
    32500 AS video_midpoints,
    22750 AS video_third_quartile_completes,
    19500 AS video_completions,
    0.3000 AS video_completion_rate,
    315.0 AS conversions,
    185.0 AS post_click_conversions,
    130.0 AS post_view_conversions,
    11100.0 AS post_click_revenue,
    5200.0 AS post_view_revenue,
    0.0294 AS post_click_conv_rate,
    78.2 AS io_goal_pacing_pct,
    14.8 AS lost_is_budget,
    8.2 AS lost_is_rank
  ),
  STRUCT(
    CURRENT_DATE() AS date,
    'io_203' AS insertion_order_id,
    'Starlight - Overpacing Blitz' AS insertion_order_name,
    'ENTITY_STATUS_ACTIVE' AS entity_status,
    'cmp_1003' AS campaign_id,
    'Starlight - DG Direct Action Drive' AS campaign_name,
    'adv_8803' AS advertiser_id,
    'adv_8803' AS account_id,
    'Starlight Media' AS account_name,
    '⚪ NOT_CONFIGURED' AS gtg_status,
    'WEB_TAG_TYPE_NONE' AS web_tag_type,
    'partner_9901' AS partner_id,
    'GBP' AS currency_code,
    'PACING_TYPE_ASAP' AS pacing_type,
    'PACING_PERIOD_FLIGHT' AS pacing_period,
    1500.0 AS daily_max_amount,
    'BUDGET_UNIT_CURRENCY' AS budget_unit,
    10000.0 AS budget_amount,
    DATE_SUB(CURRENT_DATE(), INTERVAL 5 DAY) AS start_date,
    DATE_ADD(CURRENT_DATE(), INTERVAL 15 DAY) AS end_date,
    5800.0 AS cumulative_spend,
    7540.0 AS cumulative_spend_usd,
    20 AS total_flight_days,
    5 AS elapsed_flight_days,
    15 AS remaining_flight_days,
    25.0 AS flight_elapsed_pct,
    58.0 AS budget_spent_pct,
    232.0 AS pacing_index_pct,
    500.0 AS target_daily_budget,
    1160.0 AS current_daily_burn_rate,
    280.0 AS required_daily_burn_rate,
    23200.0 AS projected_flight_spend,
    0.0 AS budget_at_risk,
    0.0 AS budget_at_risk_usd,
    '🔴 OVERPACING' AS pacing_status,
    95000 AS impressions,
    2850 AS clicks,
    3200.0 AS cost,
    4160.0 AS cost_usd,
    0.0300 AS ctr,
    1.1228 AS cpc,
    1.4596 AS cpc_usd,
    33.68 AS cpm,
    43.79 AS cpm_usd,
    66500 AS active_view_viewable_impressions,
    80750 AS active_view_measurable_impressions,
    95000 AS active_view_eligible_impressions,
    0.8235 AS viewability_rate,
    0.8500 AS measurable_rate,
    21000 AS trueview_views,
    0.2211 AS vtr,
    28000 AS video_plays,
    19600 AS video_first_quartile_completes,
    14000 AS video_midpoints,
    9800 AS video_third_quartile_completes,
    8400 AS video_completions,
    0.3000 AS video_completion_rate,
    120.0 AS conversions,
    75.0 AS post_click_conversions,
    45.0 AS post_view_conversions,
    3750.0 AS post_click_revenue,
    1800.0 AS post_view_revenue,
    0.0263 AS post_click_conv_rate,
    88.0 AS io_goal_pacing_pct,
    5.4 AS lost_is_budget,
    6.1 AS lost_is_rank
  ),
  STRUCT(
    CURRENT_DATE() AS date,
    'io_204' AS insertion_order_id,
    'Acme - Summer Flash Sale (Exhausted)' AS insertion_order_name,
    'ENTITY_STATUS_ACTIVE' AS entity_status,
    'cmp_1001' AS campaign_id,
    'Acme Global - Demand Gen Q3 Brand Launch' AS campaign_name,
    'adv_8801' AS advertiser_id,
    'adv_8801' AS account_id,
    'Acme Retail Global' AS account_name,
    '🟢 READY' AS gtg_status,
    'WEB_TAG_TYPE_DYNAMIC' AS web_tag_type,
    'partner_9901' AS partner_id,
    'USD' AS currency_code,
    'PACING_TYPE_ASAP' AS pacing_type,
    'PACING_PERIOD_FLIGHT' AS pacing_period,
    2000.0 AS daily_max_amount,
    'BUDGET_UNIT_CURRENCY' AS budget_unit,
    15000.0 AS budget_amount,
    DATE_SUB(CURRENT_DATE(), INTERVAL 10 DAY) AS start_date,
    DATE_ADD(CURRENT_DATE(), INTERVAL 5 DAY) AS end_date,
    15000.0 AS cumulative_spend,
    15000.0 AS cumulative_spend_usd,
    15 AS total_flight_days,
    10 AS elapsed_flight_days,
    5 AS remaining_flight_days,
    66.67 AS flight_elapsed_pct,
    100.0 AS budget_spent_pct,
    150.0 AS pacing_index_pct,
    1000.0 AS target_daily_budget,
    1500.0 AS current_daily_burn_rate,
    0.0 AS required_daily_burn_rate,
    15000.0 AS projected_flight_spend,
    0.0 AS budget_at_risk,
    0.0 AS budget_at_risk_usd,
    '🔴 BUDGET_EXHAUSTED' AS pacing_status,
    420000 AS impressions,
    15000 AS clicks,
    15000.0 AS cost,
    15000.0 AS cost_usd,
    0.0357 AS ctr,
    1.0000 AS cpc,
    1.0000 AS cpc_usd,
    35.71 AS cpm,
    35.71 AS cpm_usd,
    310000 AS active_view_viewable_impressions,
    350000 AS active_view_measurable_impressions,
    420000 AS active_view_eligible_impressions,
    0.8857 AS viewability_rate,
    0.8333 AS measurable_rate,
    95000 AS trueview_views,
    0.2262 AS vtr,
    110000 AS video_plays,
    82500 AS video_first_quartile_completes,
    55000 AS video_midpoints,
    38500 AS video_third_quartile_completes,
    33000 AS video_completions,
    0.3000 AS video_completion_rate,
    750.0 AS conversions,
    500.0 AS post_click_conversions,
    250.0 AS post_view_conversions,
    22000.0 AS post_click_revenue,
    8000.0 AS post_view_revenue,
    0.0333 AS post_click_conv_rate,
    100.0 AS io_goal_pacing_pct,
    0.0 AS lost_is_budget,
    1.2 AS lost_is_rank
  ),
  STRUCT(
    CURRENT_DATE() AS date,
    'io_205' AS insertion_order_id,
    'OmniTech - Paused Retargeting' AS insertion_order_name,
    'ENTITY_STATUS_PAUSED' AS entity_status,
    'cmp_1002' AS campaign_id,
    'OmniTech - DG Mid-Funnel Considerations' AS campaign_name,
    'adv_8802' AS advertiser_id,
    'adv_8802' AS account_id,
    'OmniTech Solutions' AS account_name,
    '🔴 NEEDS_TAG_UPGRADE' AS gtg_status,
    'WEB_TAG_TYPE_IMAGE' AS web_tag_type,
    'partner_9901' AS partner_id,
    'EUR' AS currency_code,
    'PACING_TYPE_EVEN' AS pacing_type,
    'PACING_PERIOD_FLIGHT' AS pacing_period,
    500.0 AS daily_max_amount,
    'BUDGET_UNIT_CURRENCY' AS budget_unit,
    12000.0 AS budget_amount,
    DATE_SUB(CURRENT_DATE(), INTERVAL 12 DAY) AS start_date,
    DATE_ADD(CURRENT_DATE(), INTERVAL 18 DAY) AS end_date,
    3400.0 AS cumulative_spend,
    3672.0 AS cumulative_spend_usd,
    30 AS total_flight_days,
    12 AS elapsed_flight_days,
    18 AS remaining_flight_days,
    40.0 AS flight_elapsed_pct,
    28.33 AS budget_spent_pct,
    70.83 AS pacing_index_pct,
    400.0 AS target_daily_budget,
    283.33 AS current_daily_burn_rate,
    0.0 AS required_daily_burn_rate,
    8500.0 AS projected_flight_spend,
    0.0 AS budget_at_risk,
    0.0 AS budget_at_risk_usd,
    '⚪ PAUSED' AS pacing_status,
    0 AS impressions,
    0 AS clicks,
    0.0 AS cost,
    0.0 AS cost_usd,
    0.0 AS ctr,
    0.0 AS cpc,
    0.0 AS cpc_usd,
    0.0 AS cpm,
    0.0 AS cpm_usd,
    0 AS active_view_viewable_impressions,
    0 AS active_view_measurable_impressions,
    0 AS active_view_eligible_impressions,
    0.0 AS viewability_rate,
    0.0 AS measurable_rate,
    0 AS trueview_views,
    0.0 AS vtr,
    0 AS video_plays,
    0 AS video_first_quartile_completes,
    0 AS video_midpoints,
    0 AS video_third_quartile_completes,
    0 AS video_completions,
    0.0 AS video_completion_rate,
    0.0 AS conversions,
    0.0 AS post_click_conversions,
    0.0 AS post_view_conversions,
    0.0 AS post_click_revenue,
    0.0 AS post_view_revenue,
    0.0 AS post_click_conv_rate,
    0.0 AS io_goal_pacing_pct,
    0.0 AS lost_is_budget,
    0.0 AS lost_is_rank
  ),
  STRUCT(
    CURRENT_DATE() AS date,
    'io_206' AS insertion_order_id,
    'Starlight - Evergreen Brand Always-On' AS insertion_order_name,
    'ENTITY_STATUS_ACTIVE' AS entity_status,
    'cmp_1003' AS campaign_id,
    'Starlight - DG Direct Action Drive' AS campaign_name,
    'adv_8803' AS advertiser_id,
    'adv_8803' AS account_id,
    'Starlight Media' AS account_name,
    '⚪ NOT_CONFIGURED' AS gtg_status,
    'WEB_TAG_TYPE_NONE' AS web_tag_type,
    'partner_9901' AS partner_id,
    'GBP' AS currency_code,
    'PACING_TYPE_EVEN' AS pacing_type,
    'PACING_PERIOD_FLIGHT' AS pacing_period,
    0.0 AS daily_max_amount,
    'BUDGET_UNIT_CURRENCY' AS budget_unit,
    0.0 AS budget_amount,
    DATE_SUB(CURRENT_DATE(), INTERVAL 30 DAY) AS start_date,
    DATE_ADD(CURRENT_DATE(), INTERVAL 60 DAY) AS end_date,
    4200.0 AS cumulative_spend,
    5460.0 AS cumulative_spend_usd,
    90 AS total_flight_days,
    30 AS elapsed_flight_days,
    60 AS remaining_flight_days,
    33.33 AS flight_elapsed_pct,
    0.0 AS budget_spent_pct,
    0.0 AS pacing_index_pct,
    0.0 AS target_daily_budget,
    140.0 AS current_daily_burn_rate,
    0.0 AS required_daily_burn_rate,
    12600.0 AS projected_flight_spend,
    0.0 AS budget_at_risk,
    0.0 AS budget_at_risk_usd,
    '⚪ NO_BUDGET_SET' AS pacing_status,
    60000 AS impressions,
    1800 AS clicks,
    1800.0 AS cost,
    2340.0 AS cost_usd,
    0.0300 AS ctr,
    1.0000 AS cpc,
    1.3000 AS cpc_usd,
    30.00 AS cpm,
    39.00 AS cpm_usd,
    42000 AS active_view_viewable_impressions,
    51000 AS active_view_measurable_impressions,
    60000 AS active_view_eligible_impressions,
    0.8235 AS viewability_rate,
    0.8500 AS measurable_rate,
    14000 AS trueview_views,
    0.2333 AS vtr,
    18000 AS video_plays,
    12600 AS video_first_quartile_completes,
    9000 AS video_midpoints,
    6300 AS video_third_quartile_completes,
    5400 AS video_completions,
    0.3000 AS video_completion_rate,
    65.0 AS conversions,
    40.0 AS post_click_conversions,
    25.0 AS post_view_conversions,
    1800.0 AS post_click_revenue,
    900.0 AS post_view_revenue,
    0.0222 AS post_click_conv_rate,
    0.0 AS io_goal_pacing_pct,
    1.2 AS lost_is_budget,
    2.4 AS lost_is_rank
  ),
  STRUCT(
    CURRENT_DATE() AS date,
    'io_207' AS insertion_order_id,
    'Acme - Q4 Holiday Teaser' AS insertion_order_name,
    'ENTITY_STATUS_ACTIVE' AS entity_status,
    'cmp_1001' AS campaign_id,
    'Acme Global - Demand Gen Q3 Brand Launch' AS campaign_name,
    'adv_8801' AS advertiser_id,
    'adv_8801' AS account_id,
    'Acme Retail Global' AS account_name,
    '🟢 READY' AS gtg_status,
    'WEB_TAG_TYPE_DYNAMIC' AS web_tag_type,
    'partner_9901' AS partner_id,
    'USD' AS currency_code,
    'PACING_TYPE_EVEN' AS pacing_type,
    'PACING_PERIOD_FLIGHT' AS pacing_period,
    1000.0 AS daily_max_amount,
    'BUDGET_UNIT_CURRENCY' AS budget_unit,
    20000.0 AS budget_amount,
    DATE_ADD(CURRENT_DATE(), INTERVAL 5 DAY) AS start_date,
    DATE_ADD(CURRENT_DATE(), INTERVAL 35 DAY) AS end_date,
    0.0 AS cumulative_spend,
    0.0 AS cumulative_spend_usd,
    30 AS total_flight_days,
    0 AS elapsed_flight_days,
    30 AS remaining_flight_days,
    0.0 AS flight_elapsed_pct,
    0.0 AS budget_spent_pct,
    0.0 AS pacing_index_pct,
    666.67 AS target_daily_budget,
    0.0 AS current_daily_burn_rate,
    666.67 AS required_daily_burn_rate,
    0.0 AS projected_flight_spend,
    0.0 AS budget_at_risk,
    0.0 AS budget_at_risk_usd,
    '⚪ UPCOMING' AS pacing_status,
    0 AS impressions,
    0 AS clicks,
    0.0 AS cost,
    0.0 AS cost_usd,
    0.0 AS ctr,
    0.0 AS cpc,
    0.0 AS cpc_usd,
    0.0 AS cpm,
    0.0 AS cpm_usd,
    0 AS active_view_viewable_impressions,
    0 AS active_view_measurable_impressions,
    0 AS active_view_eligible_impressions,
    0.0 AS viewability_rate,
    0.0 AS measurable_rate,
    0 AS trueview_views,
    0.0 AS vtr,
    0 AS video_plays,
    0 AS video_first_quartile_completes,
    0 AS video_midpoints,
    0 AS video_third_quartile_completes,
    0 AS video_completions,
    0.0 AS video_completion_rate,
    0.0 AS conversions,
    0.0 AS post_click_conversions,
    0.0 AS post_view_conversions,
    0.0 AS post_click_revenue,
    0.0 AS post_view_revenue,
    0.0 AS post_click_conv_rate,
    0.0 AS io_goal_pacing_pct,
    0.0 AS lost_is_budget,
    0.0 AS lost_is_rank
  ),
  STRUCT(
    CURRENT_DATE() AS date,
    'io_208' AS insertion_order_id,
    'OmniTech - Q2 Spring Sprint (Closed Under)' AS insertion_order_name,
    'ENTITY_STATUS_ACTIVE' AS entity_status,
    'cmp_1002' AS campaign_id,
    'OmniTech - DG Mid-Funnel Considerations' AS campaign_name,
    'adv_8802' AS advertiser_id,
    'adv_8802' AS account_id,
    'OmniTech Solutions' AS account_name,
    '🔴 NEEDS_TAG_UPGRADE' AS gtg_status,
    'WEB_TAG_TYPE_IMAGE' AS web_tag_type,
    'partner_9901' AS partner_id,
    'EUR' AS currency_code,
    'PACING_TYPE_EVEN' AS pacing_type,
    'PACING_PERIOD_FLIGHT' AS pacing_period,
    1000.0 AS daily_max_amount,
    'BUDGET_UNIT_CURRENCY' AS budget_unit,
    20000.0 AS budget_amount,
    DATE_SUB(CURRENT_DATE(), INTERVAL 45 DAY) AS start_date,
    DATE_SUB(CURRENT_DATE(), INTERVAL 15 DAY) AS end_date,
    13200.0 AS cumulative_spend,
    14256.0 AS cumulative_spend_usd,
    30 AS total_flight_days,
    30 AS elapsed_flight_days,
    0 AS remaining_flight_days,
    100.0 AS flight_elapsed_pct,
    66.0 AS budget_spent_pct,
    66.0 AS pacing_index_pct,
    666.67 AS target_daily_budget,
    440.0 AS current_daily_burn_rate,
    0.0 AS required_daily_burn_rate,
    13200.0 AS projected_flight_spend,
    0.0 AS budget_at_risk,
    0.0 AS budget_at_risk_usd,
    '🟡 UNDERSPENT_FINISHED' AS pacing_status,
    0 AS impressions,
    0 AS clicks,
    0.0 AS cost,
    0.0 AS cost_usd,
    0.0 AS ctr,
    0.0 AS cpc,
    0.0 AS cpc_usd,
    0.0 AS cpm,
    0.0 AS cpm_usd,
    0 AS active_view_viewable_impressions,
    0 AS active_view_measurable_impressions,
    0 AS active_view_eligible_impressions,
    0.0 AS viewability_rate,
    0.0 AS measurable_rate,
    0 AS trueview_views,
    0.0 AS vtr,
    0 AS video_plays,
    0 AS video_first_quartile_completes,
    0 AS video_midpoints,
    0 AS video_third_quartile_completes,
    0 AS video_completions,
    0.0 AS video_completion_rate,
    0.0 AS conversions,
    0.0 AS post_click_conversions,
    0.0 AS post_view_conversions,
    0.0 AS post_click_revenue,
    0.0 AS post_view_revenue,
    0.0 AS post_click_conv_rate,
    0.0 AS io_goal_pacing_pct,
    0.0 AS lost_is_budget,
    0.0 AS lost_is_rank
  ),
  STRUCT(
    CURRENT_DATE() AS date,
    'io_209' AS insertion_order_id,
    'Acme - Prime Brand Awareness (Completed)' AS insertion_order_name,
    'ENTITY_STATUS_ACTIVE' AS entity_status,
    'cmp_1001' AS campaign_id,
    'Acme Global - Demand Gen Q3 Brand Launch' AS campaign_name,
    'adv_8801' AS advertiser_id,
    'adv_8801' AS account_id,
    'Acme Retail Global' AS account_name,
    '🟢 READY' AS gtg_status,
    'WEB_TAG_TYPE_DYNAMIC' AS web_tag_type,
    'partner_9901' AS partner_id,
    'USD' AS currency_code,
    'PACING_TYPE_EVEN' AS pacing_type,
    'PACING_PERIOD_FLIGHT' AS pacing_period,
    1000.0 AS daily_max_amount,
    'BUDGET_UNIT_CURRENCY' AS budget_unit,
    25000.0 AS budget_amount,
    DATE_SUB(CURRENT_DATE(), INTERVAL 60 DAY) AS start_date,
    DATE_SUB(CURRENT_DATE(), INTERVAL 5 DAY) AS end_date,
    25000.0 AS cumulative_spend,
    25000.0 AS cumulative_spend_usd,
    55 AS total_flight_days,
    55 AS elapsed_flight_days,
    0 AS remaining_flight_days,
    100.0 AS flight_elapsed_pct,
    100.0 AS budget_spent_pct,
    100.0 AS pacing_index_pct,
    454.55 AS target_daily_budget,
    454.55 AS current_daily_burn_rate,
    0.0 AS required_daily_burn_rate,
    25000.0 AS projected_flight_spend,
    0.0 AS budget_at_risk,
    0.0 AS budget_at_risk_usd,
    '⚪ COMPLETED' AS pacing_status,
    0 AS impressions,
    0 AS clicks,
    0.0 AS cost,
    0.0 AS cost_usd,
    0.0 AS ctr,
    0.0 AS cpc,
    0.0 AS cpc_usd,
    0.0 AS cpm,
    0.0 AS cpm_usd,
    0 AS active_view_viewable_impressions,
    0 AS active_view_measurable_impressions,
    0 AS active_view_eligible_impressions,
    0.0 AS viewability_rate,
    0.0 AS measurable_rate,
    0 AS trueview_views,
    0.0 AS vtr,
    0 AS video_plays,
    0 AS video_first_quartile_completes,
    0 AS video_midpoints,
    0 AS video_third_quartile_completes,
    0 AS video_completions,
    0.0 AS video_completion_rate,
    0.0 AS conversions,
    0.0 AS post_click_conversions,
    0.0 AS post_view_conversions,
    0.0 AS post_click_revenue,
    0.0 AS post_view_revenue,
    0.0 AS post_click_conv_rate,
    0.0 AS io_goal_pacing_pct,
    0.0 AS lost_is_budget,
    0.0 AS lost_is_rank
  )
]);

-- 4. ASSETS PERFORMANCE (final_assets_performance)
CREATE OR REPLACE TABLE `__PROJECT_ID__.__DATASET_ID__.final_assets_performance` AS
SELECT * FROM UNNEST([
  STRUCT(
    CURRENT_DATE() AS date,
    'ast_101' AS asset_id,
    'aga_901' AS ad_group_ad_id,
    'dQw4w9WgXcQ' AS video_id,
    'Acme Brand Hero - Landscape 16:9' AS asset_name,
    'YOUTUBE VIDEO' AS asset_type,
    'LANDSCAPE' AS asset_variant,
    '1920x1080' AS creative_dimensions,
    'https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg' AS image_url,
    'HOSTING_SOURCE_YOUTUBE' AS hosting_source,
    'ENTITY_STATUS_ACTIVE' AS entity_status,
    'APPROVED' AS approval_status,
    'io_201' AS insertion_order_id,
    'Acme Q3 - On Track Flight' AS insertion_order_name,
    'li_501' AS line_item_id,
    'Acme - DG Video Action - YouTube Shorts' AS line_item_name,
    'adv_8801' AS advertiser_id,
    'adv_8801' AS account_id,
    'Acme Retail Global' AS account_name,
    'cmp_1001' AS campaign_id,
    'Acme Global - Demand Gen Q3 Brand Launch' AS campaign_name,
    'USD' AS currency_code,
    'partner_9901' AS partner_id,
    185000 AS impressions,
    4200 AS clicks,
    1850.25 AS cost,
    95.0 AS conversions,
    0.0227 AS ctr,
    0.44 AS cpc,
    10.00 AS cpm,
    'https://www.youtube.com/watch?v=dQw4w9WgXcQ' AS asset_link,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8801/c/cmp_1001/io/io_201/li/li_501/adgroups' AS dv360_url,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8801/c/cmp_1001/io/io_201/li/li_501/adgroups' AS line_item_link,
    'https://www.youtube.com/watch?v=dQw4w9WgXcQ' AS youtube_url
  ),
  STRUCT(
    CURRENT_DATE() AS date,
    'ast_102' AS asset_id,
    'aga_902' AS ad_group_ad_id,
    'kJQP7kiw5Fk' AS video_id,
    'Acme Shorts - Vertical 9:16 Action' AS asset_name,
    'YOUTUBE VIDEO' AS asset_type,
    'VERTICAL' AS asset_variant,
    '1080x1920' AS creative_dimensions,
    'https://img.youtube.com/vi/kJQP7kiw5Fk/hqdefault.jpg' AS image_url,
    'HOSTING_SOURCE_YOUTUBE' AS hosting_source,
    'ENTITY_STATUS_ACTIVE' AS entity_status,
    'APPROVED' AS approval_status,
    'io_201' AS insertion_order_id,
    'Acme Q3 - On Track Flight' AS insertion_order_name,
    'li_501' AS line_item_id,
    'Acme - DG Video Action - YouTube Shorts' AS line_item_name,
    'adv_8801' AS advertiser_id,
    'adv_8801' AS account_id,
    'Acme Retail Global' AS account_name,
    'cmp_1001' AS campaign_id,
    'Acme Global - Demand Gen Q3 Brand Launch' AS campaign_name,
    'USD' AS currency_code,
    'partner_9901' AS partner_id,
    220000 AS impressions,
    6500 AS clicks,
    1680.00 AS cost,
    142.0 AS conversions,
    0.0295 AS ctr,
    0.26 AS cpc,
    7.64 AS cpm,
    'https://www.youtube.com/watch?v=kJQP7kiw5Fk' AS asset_link,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8801/c/cmp_1001/io/io_201/li/li_501/adgroups' AS dv360_url,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8801/c/cmp_1001/io/io_201/li/li_501/adgroups' AS line_item_link,
    'https://www.youtube.com/watch?v=kJQP7kiw5Fk' AS youtube_url
  ),
  STRUCT(
    CURRENT_DATE() AS date,
    'ast_103' AS asset_id,
    'aga_903' AS ad_group_ad_id,
    CAST(NULL AS STRING) AS video_id,
    'Acme Product Showcase - Square 1:1' AS asset_name,
    'SQUARE IMAGE' AS asset_type,
    'SQUARE' AS asset_variant,
    '1200x1200' AS creative_dimensions,
    'https://www.gstatic.com/images/branding/googleg/1x/googleg_standard_color_128dp.png' AS image_url,
    'HOSTING_SOURCE_INTERNAL' AS hosting_source,
    'ENTITY_STATUS_ACTIVE' AS entity_status,
    'APPROVED' AS approval_status,
    'io_201' AS insertion_order_id,
    'Acme Q3 - On Track Flight' AS insertion_order_name,
    'li_502' AS line_item_id,
    'Acme - DG Multi-Format Display & Discover' AS line_item_name,
    'adv_8801' AS advertiser_id,
    'adv_8801' AS account_id,
    'Acme Retail Global' AS account_name,
    'cmp_1001' AS campaign_id,
    'Acme Global - Demand Gen Q3 Brand Launch' AS campaign_name,
    'USD' AS currency_code,
    'partner_9901' AS partner_id,
    95000 AS impressions,
    2100 AS clicks,
    820.50 AS cost,
    48.0 AS conversions,
    0.0221 AS ctr,
    0.39 AS cpc,
    8.64 AS cpm,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8801/c/cmp_1001/io/io_201/li/li_502/adgroups' AS asset_link,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8801/c/cmp_1001/io/io_201/li/li_502/adgroups' AS dv360_url,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8801/c/cmp_1001/io/io_201/li/li_502/adgroups' AS line_item_link,
    CAST(NULL AS STRING) AS youtube_url
  ),
  STRUCT(
    CURRENT_DATE() AS date,
    'ast_104' AS asset_id,
    'aga_904' AS ad_group_ad_id,
    CAST(NULL AS STRING) AS video_id,
    'Acme Lifestyle Banner - Landscape 1.91:1' AS asset_name,
    'MARKETING IMAGE' AS asset_type,
    'LANDSCAPE' AS asset_variant,
    '1200x628' AS creative_dimensions,
    'https://www.gstatic.com/images/branding/googleg/1x/googleg_standard_color_128dp.png' AS image_url,
    'HOSTING_SOURCE_INTERNAL' AS hosting_source,
    'ENTITY_STATUS_ACTIVE' AS entity_status,
    'APPROVED' AS approval_status,
    'io_201' AS insertion_order_id,
    'Acme Q3 - On Track Flight' AS insertion_order_name,
    'li_502' AS line_item_id,
    'Acme - DG Multi-Format Display & Discover' AS line_item_name,
    'adv_8801' AS advertiser_id,
    'adv_8801' AS account_id,
    'Acme Retail Global' AS account_name,
    'cmp_1001' AS campaign_id,
    'Acme Global - Demand Gen Q3 Brand Launch' AS campaign_name,
    'USD' AS currency_code,
    'partner_9901' AS partner_id,
    72000 AS impressions,
    1450 AS clicks,
    610.00 AS cost,
    31.0 AS conversions,
    0.0201 AS ctr,
    0.42 AS cpc,
    8.47 AS cpm,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8801/c/cmp_1001/io/io_201/li/li_502/adgroups' AS asset_link,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8801/c/cmp_1001/io/io_201/li/li_502/adgroups' AS dv360_url,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8801/c/cmp_1001/io/io_201/li/li_502/adgroups' AS line_item_link,
    CAST(NULL AS STRING) AS youtube_url
  ),
  STRUCT(
    CURRENT_DATE() AS date,
    'ast_105' AS asset_id,
    'aga_905' AS ad_group_ad_id,
    CAST(NULL AS STRING) AS video_id,
    'OmniTech Solution Pitch - Portrait 4:5' AS asset_name,
    'VERTICAL IMAGE' AS asset_type,
    'VERTICAL' AS asset_variant,
    '960x1200' AS creative_dimensions,
    'https://www.gstatic.com/images/branding/googleg/1x/googleg_standard_color_128dp.png' AS image_url,
    'HOSTING_SOURCE_INTERNAL' AS hosting_source,
    'ENTITY_STATUS_ACTIVE' AS entity_status,
    'APPROVED' AS approval_status,
    'io_202' AS insertion_order_id,
    'OmniTech - Underpacing Flight' AS insertion_order_name,
    'li_503' AS line_item_id,
    'OmniTech - DG In-Market Consideration' AS line_item_name,
    'adv_8802' AS advertiser_id,
    'adv_8802' AS account_id,
    'OmniTech Solutions' AS account_name,
    'cmp_1002' AS campaign_id,
    'OmniTech - DG Mid-Funnel Considerations' AS campaign_name,
    'EUR' AS currency_code,
    'partner_9901' AS partner_id,
    64000 AS impressions,
    1180 AS clicks,
    550.00 AS cost,
    19.0 AS conversions,
    0.0184 AS ctr,
    0.47 AS cpc,
    8.59 AS cpm,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8802/c/cmp_1002/io/io_202/li/li_503/adgroups' AS asset_link,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8802/c/cmp_1002/io/io_202/li/li_503/adgroups' AS dv360_url,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8802/c/cmp_1002/io/io_202/li/li_503/adgroups' AS line_item_link,
    CAST(NULL AS STRING) AS youtube_url
  )
]);

-- 5. CREATIVE VARIETY (final_creative_variety)
CREATE OR REPLACE TABLE `__PROJECT_ID__.__DATASET_ID__.final_creative_variety` AS
SELECT * FROM UNNEST([
  STRUCT(
    'io_201' AS insertion_order_id,
    'Acme Q3 - On Track Flight' AS insertion_order_name,
    'Acme Multi-Format Omni Ad' AS ad_name,
    'DEMAND_GEN_VIDEO_AD' AS ad_type,
    'aga_901' AS ad_group_ad_id,
    'cmp_1001' AS campaign_id,
    'Acme Global - Demand Gen Q3 Brand Launch' AS campaign_name,
    'adv_8801' AS advertiser_id,
    'adv_8801' AS account_id,
    'Acme Retail Global' AS account_name,
    'partner_9901' AS partner_id,
    'YES' AS image_and_video,
    2 AS vertical_videos,
    2 AS horizontal_videos,
    1 AS square_videos,
    4 AS horizontal_images,
    3 AS vertical_images,
    3 AS square_images,
    5 AS headlines,
    5 AS descriptions,
    'NO' AS product_feed,
    'PASSED' AS asset_coverage_status
  ),
  STRUCT(
    'io_202' AS insertion_order_id,
    'OmniTech - Underpacing Flight' AS insertion_order_name,
    'OmniTech Image Only Ad' AS ad_name,
    'DEMAND_GEN_IMAGE_AD' AS ad_type,
    'aga_905' AS ad_group_ad_id,
    'cmp_1002' AS campaign_id,
    'OmniTech - DG Mid-Funnel Considerations' AS campaign_name,
    'adv_8802' AS advertiser_id,
    'adv_8802' AS account_id,
    'OmniTech Solutions' AS account_name,
    'partner_9901' AS partner_id,
    'NO' AS image_and_video,
    0 AS vertical_videos,
    0 AS horizontal_videos,
    0 AS square_videos,
    2 AS horizontal_images,
    1 AS vertical_images,
    1 AS square_images,
    3 AS headlines,
    2 AS descriptions,
    'NO' AS product_feed,
    'NEEDS_ACTION' AS asset_coverage_status
  ),
  STRUCT(
    'io_203' AS insertion_order_id,
    'Starlight - Overpacing Blitz' AS insertion_order_name,
    'Starlight Shorts Only' AS ad_name,
    'DEMAND_GEN_VIDEO_AD' AS ad_type,
    'aga_906' AS ad_group_ad_id,
    'cmp_1003' AS campaign_id,
    'Starlight - DG Direct Action Drive' AS campaign_name,
    'adv_8803' AS advertiser_id,
    'adv_8803' AS account_id,
    'Starlight Media' AS account_name,
    'partner_9901' AS partner_id,
    'NO' AS image_and_video,
    1 AS vertical_videos,
    0 AS horizontal_videos,
    0 AS square_videos,
    0 AS horizontal_images,
    0 AS vertical_images,
    0 AS square_images,
    2 AS headlines,
    2 AS descriptions,
    'NO' AS product_feed,
    'PASSED' AS asset_coverage_status
  )
]);

-- 6. AUDIENCES PERFORMANCE (final_audiences_performance)
CREATE OR REPLACE TABLE `__PROJECT_ID__.__DATASET_ID__.final_audiences_performance` AS
SELECT * FROM UNNEST([
  STRUCT(
    DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY) AS date,
    'partner_9901' AS partner_id,
    'adv_8801' AS advertiser_id,
    'adv_8801' AS account_id,
    'Acme Retail Global' AS account_name,
    'cmp_1001' AS campaign_id,
    'Acme Global - Demand Gen Q3 Brand Launch' AS campaign_name,
    'io_201' AS insertion_order_id,
    'Acme Q3 - On Track Flight' AS insertion_order_name,
    'li_501' AS line_item_id,
    'Acme - DG Video Action - YouTube Shorts' AS line_item_name,
    'aud_7001' AS audience_id,
    'High Value CRM Customers (1PD)' AS audience_segment,
    'USER_LIST (1PD)' AS audience_type,
    'YES' AS is_first_party,
    'USD' AS currency_code,
    140000 AS impressions,
    6200 AS clicks,
    3800.0 AS cost,
    3800.0 AS cost_usd,
    380.0 AS conversions,
    120.0 AS vtc,
    10.00 AS cpa,
    10.00 AS cpa_usd,
    4.50 AS roas,
    0.6129 AS avg_cpc,
    0.6129 AS avg_cpc_usd
  ),
  STRUCT(
    DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY) AS date,
    'partner_9901' AS partner_id,
    'adv_8801' AS advertiser_id,
    'adv_8801' AS account_id,
    'Acme Retail Global' AS account_name,
    'cmp_1001' AS campaign_id,
    'Acme Global - Demand Gen Q3 Brand Launch' AS campaign_name,
    'io_201' AS insertion_order_id,
    'Acme Q3 - On Track Flight' AS insertion_order_name,
    'li_501' AS line_item_id,
    'Acme - DG Video Action - YouTube Shorts' AS line_item_name,
    'aud_7002' AS audience_id,
    'Website Cart Abandoners - 30 Days' AS audience_segment,
    'USER_LIST (1PD)' AS audience_type,
    'YES' AS is_first_party,
    'USD' AS currency_code,
    85000 AS impressions,
    3600 AS clicks,
    2400.0 AS cost,
    2400.0 AS cost_usd,
    210.0 AS conversions,
    65.0 AS vtc,
    11.43 AS cpa,
    11.43 AS cpa_usd,
    3.80 AS roas,
    0.6667 AS avg_cpc,
    0.6667 AS avg_cpc_usd
  ),
  STRUCT(
    DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY) AS date,
    'partner_9901' AS partner_id,
    'adv_8801' AS advertiser_id,
    'adv_8801' AS account_id,
    'Acme Retail Global' AS account_name,
    'cmp_1001' AS campaign_id,
    'Acme Global - Demand Gen Q3 Brand Launch' AS campaign_name,
    'io_201' AS insertion_order_id,
    'Acme Q3 - On Track Flight' AS insertion_order_name,
    'li_502' AS line_item_id,
    'Acme - DG Multi-Format Display & Discover' AS line_item_name,
    'aud_7003' AS audience_id,
    'Similar to Top 5% Purchasing Customers' AS audience_segment,
    'LOOKALIKE' AS audience_type,
    'NO' AS is_first_party,
    'USD' AS currency_code,
    120000 AS impressions,
    4400 AS clicks,
    4100.0 AS cost,
    4100.0 AS cost_usd,
    180.0 AS conversions,
    85.0 AS vtc,
    22.78 AS cpa,
    22.78 AS cpa_usd,
    2.60 AS roas,
    0.9318 AS avg_cpc,
    0.9318 AS avg_cpc_usd
  ),
  STRUCT(
    DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY) AS date,
    'partner_9901' AS partner_id,
    'adv_8801' AS advertiser_id,
    'adv_8801' AS account_id,
    'Acme Retail Global' AS account_name,
    'cmp_1001' AS campaign_id,
    'Acme Global - Demand Gen Q3 Brand Launch' AS campaign_name,
    'io_201' AS insertion_order_id,
    'Acme Q3 - On Track Flight' AS insertion_order_name,
    'li_502' AS line_item_id,
    'Acme - DG Multi-Format Display & Discover' AS line_item_name,
    'aud_7004' AS audience_id,
    'In-Market: Retail & Apparel Shoppers' AS audience_segment,
    'USER_INTEREST (Google Audience)' AS audience_type,
    'NO' AS is_first_party,
    'USD' AS currency_code,
    105000 AS impressions,
    4000 AS clicks,
    4200.0 AS cost,
    4200.0 AS cost_usd,
    210.0 AS conversions,
    90.0 AS vtc,
    20.00 AS cpa,
    20.00 AS cpa_usd,
    2.80 AS roas,
    1.0500 AS avg_cpc,
    1.0500 AS avg_cpc_usd
  )
]);

-- 7. FLOODLIGHT ACTIVITIES AUDIT (final_floodlight_activities_audit)
CREATE OR REPLACE TABLE `__PROJECT_ID__.__DATASET_ID__.final_floodlight_activities_audit` AS
SELECT * FROM UNNEST([
  STRUCT(
    CURRENT_DATE() AS date,
    'fl_3001' AS activity_id,
    'Purchase / Order Confirmation - Modern Google Tag' AS activity_name,
    'adv_8801' AS advertiser_id,
    'partner_9901' AS partner_id,
    'flg_501' AS floodlight_group_id,
    'Acme Retail Global' AS account_name,
    'FLOODLIGHT_ACTIVITY_SERVING_STATUS_ENABLED' AS serving_status,
    'WEB_TAG_TYPE_DYNAMIC' AS web_tag_type,
    30 AS click_lookback_days,
    7 AS impression_lookback_days,
    'OPTIMAL' AS attribution_lookback_status,
    'YES' AS ssl_required,
    'SSL_COMPLIANT' AS ssl_compliance_status,
    'YES' AS remarketing_enabled,
    'YES' AS ec_enabled,
    'YES' AS youtube_enabled,
    '🟢 READY' AS gtg_status,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8801/fl/fle/fl_3001/details' AS dv360_activity_url,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8801/fl/details' AS dv360_floodlight_group_url,
    '✅ Enabled' AS cls_youtube_status,
    '✅ Dynamic Tag' AS cls_dynamic_tag_status,
    '✅ Active' AS cls_ec_status,
    '✅ DDA Active' AS cls_dda_status,
    '🟢 Ready' AS cls_gtg_status
  ),
  STRUCT(
    CURRENT_DATE() AS date,
    'fl_3002' AS activity_id,
    'Lead Form Submission - Legacy Image Tag' AS activity_name,
    'adv_8802' AS advertiser_id,
    'partner_9901' AS partner_id,
    'flg_502' AS floodlight_group_id,
    'OmniTech Solutions' AS account_name,
    'FLOODLIGHT_ACTIVITY_SERVING_STATUS_ENABLED' AS serving_status,
    'WEB_TAG_TYPE_IMAGE' AS web_tag_type,
    30 AS click_lookback_days,
    1 AS impression_lookback_days,
    'OPTIMAL' AS attribution_lookback_status,
    'YES' AS ssl_required,
    'SSL_COMPLIANT' AS ssl_compliance_status,
    'YES' AS remarketing_enabled,
    'NO' AS ec_enabled,
    'NO' AS youtube_enabled,
    '🔴 NEEDS_TAG_UPGRADE' AS gtg_status,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8802/fl/fle/fl_3002/details' AS dv360_activity_url,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8802/fl/details' AS dv360_floodlight_group_url,
    '❌ Needs Setup' AS cls_youtube_status,
    '❌ Image Tag' AS cls_dynamic_tag_status,
    '❌ Not Enabled' AS cls_ec_status,
    '🟡 Last Interaction' AS cls_dda_status,
    '🔴 Needs Upgrade' AS cls_gtg_status
  ),
  STRUCT(
    CURRENT_DATE() AS date,
    'fl_3003' AS activity_id,
    'Newsletter Signup - Non-SSL Warning' AS activity_name,
    'adv_8802' AS advertiser_id,
    'partner_9901' AS partner_id,
    'flg_502' AS floodlight_group_id,
    'OmniTech Solutions' AS account_name,
    'FLOODLIGHT_ACTIVITY_SERVING_STATUS_ENABLED' AS serving_status,
    'WEB_TAG_TYPE_DYNAMIC' AS web_tag_type,
    14 AS click_lookback_days,
    1 AS impression_lookback_days,
    'OPTIMAL' AS attribution_lookback_status,
    'NO' AS ssl_required,
    'NON_SSL_COMPLIANT_WARNING' AS ssl_compliance_status,
    'NO' AS remarketing_enabled,
    'NO' AS ec_enabled,
    'NO' AS youtube_enabled,
    '🔴 NEEDS_TAG_UPGRADE' AS gtg_status,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8802/fl/fle/fl_3003/details' AS dv360_activity_url,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8802/fl/details' AS dv360_floodlight_group_url,
    '❌ Needs Setup' AS cls_youtube_status,
    '✅ Dynamic Tag' AS cls_dynamic_tag_status,
    '❌ Not Enabled' AS cls_ec_status,
    '🟡 Last Interaction' AS cls_dda_status,
    '🔴 Needs Upgrade' AS cls_gtg_status
  ),
  STRUCT(
    CURRENT_DATE() AS date,
    'fl_3004' AS activity_id,
    'App Download - 0-Day Lookback Warning' AS activity_name,
    'adv_8803' AS advertiser_id,
    'partner_9901' AS partner_id,
    'flg_503' AS floodlight_group_id,
    'Starlight Media' AS account_name,
    'FLOODLIGHT_ACTIVITY_SERVING_STATUS_ENABLED' AS serving_status,
    'WEB_TAG_TYPE_DYNAMIC' AS web_tag_type,
    0 AS click_lookback_days,
    0 AS impression_lookback_days,
    'ATTRIBUTION_WINDOW_TOO_SHORT' AS attribution_lookback_status,
    'YES' AS ssl_required,
    'SSL_COMPLIANT' AS ssl_compliance_status,
    'YES' AS remarketing_enabled,
    'NO' AS ec_enabled,
    'NO' AS youtube_enabled,
    '⚪ NOT_CONFIGURED' AS gtg_status,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8803/fl/fle/fl_3004/details' AS dv360_activity_url,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8803/fl/details' AS dv360_floodlight_group_url,
    '❌ Needs Setup' AS cls_youtube_status,
    '✅ Dynamic Tag' AS cls_dynamic_tag_status,
    '❌ Not Enabled' AS cls_ec_status,
    '🟡 Last Interaction' AS cls_dda_status,
    '🔴 Needs Upgrade' AS cls_gtg_status
  ),
  STRUCT(
    CURRENT_DATE() AS date,
    'fl_3005' AS activity_id,
    'Archived Promo Tag - Disabled Activity' AS activity_name,
    'adv_8803' AS advertiser_id,
    'partner_9901' AS partner_id,
    'flg_503' AS floodlight_group_id,
    'Starlight Media' AS account_name,
    'FLOODLIGHT_ACTIVITY_SERVING_STATUS_DISABLED' AS serving_status,
    'WEB_TAG_TYPE_NONE' AS web_tag_type,
    30 AS click_lookback_days,
    1 AS impression_lookback_days,
    'OPTIMAL' AS attribution_lookback_status,
    'YES' AS ssl_required,
    'SSL_COMPLIANT' AS ssl_compliance_status,
    'NO' AS remarketing_enabled,
    'NO' AS ec_enabled,
    'NO' AS youtube_enabled,
    '⚪ NOT_CONFIGURED' AS gtg_status,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8803/fl/fle/fl_3005/details' AS dv360_activity_url,
    'https://displayvideo.google.com/ng_nav/p/partner_9901/a/adv_8803/fl/details' AS dv360_floodlight_group_url,
    '❌ Needs Setup' AS cls_youtube_status,
    '❌ Image Tag' AS cls_dynamic_tag_status,
    '❌ Not Enabled' AS cls_ec_status,
    '🟡 Last Interaction' AS cls_dda_status,
    '🔴 Needs Upgrade' AS cls_gtg_status
  )
]);

-- 8. CONVERSION LIFT STUDIES (CLS) PRE-FLIGHT AUDIT (final_cls_preflight_audit)
CREATE OR REPLACE TABLE `__PROJECT_ID__.__DATASET_ID__.final_cls_preflight_audit` AS
SELECT * FROM UNNEST([
  -- Acme Retail Global (Ready for CLS)
  STRUCT(
    'adv_8801' AS advertiser_id,
    'Acme Retail Global' AS account_name,
    'partner_9901' AS partner_id,
    CURRENT_DATE() AS audit_date,
    1 AS check_order,
    'YouTube Enabled' AS required_check,
    '✅ Pass' AS status,
    'PASS' AS status_code,
    '1 of 1 activities enabled' AS details,
    'Set up conversion tracking for YouTube using YouTube-enabled Floodlight activities' AS steps_to_fix,
    'https://support.google.com/displayvideo/answer/12123563' AS steps_to_fix_url
  ),
  STRUCT(
    'adv_8801' AS advertiser_id,
    'Acme Retail Global' AS account_name,
    'partner_9901' AS partner_id,
    CURRENT_DATE() AS audit_date,
    2 AS check_order,
    'Dynamic Tagging' AS required_check,
    '✅ Pass' AS status,
    'PASS' AS status_code,
    '1 of 1 dynamic tags' AS details,
    'Enable dynamic tagging in Floodlight group / configuration' AS steps_to_fix,
    'https://support.google.com/campaignmanager/answer/2823194' AS steps_to_fix_url
  ),
  STRUCT(
    'adv_8801' AS advertiser_id,
    'Acme Retail Global' AS account_name,
    'partner_9901' AS partner_id,
    CURRENT_DATE() AS audit_date,
    3 AS check_order,
    'Enhanced Conversions' AS required_check,
    '✅ Pass' AS status,
    'PASS' AS status_code,
    '1 of 1 activities with EC' AS details,
    'Enable Enhanced Conversions for Floodlight at advertiser & activity levels' AS steps_to_fix,
    'https://support.google.com/campaignmanager/answer/14217426' AS steps_to_fix_url
  ),
  STRUCT(
    'adv_8801' AS advertiser_id,
    'Acme Retail Global' AS account_name,
    'partner_9901' AS partner_id,
    CURRENT_DATE() AS audit_date,
    4 AS check_order,
    'Data Driven Attribution (DDA)' AS required_check,
    '✅ Pass' AS status,
    'PASS' AS status_code,
    'Smart Bidding / DDA applied on line items' AS details,
    'Create DDA model in CM360 and apply to DV360 line items' AS steps_to_fix,
    'https://support.google.com/campaignmanager/answer/6361280' AS steps_to_fix_url
  ),
  STRUCT(
    'adv_8801' AS advertiser_id,
    'Acme Retail Global' AS account_name,
    'partner_9901' AS partner_id,
    CURRENT_DATE() AS audit_date,
    5 AS check_order,
    'Google Tag Gateway (GTG) Readiness' AS required_check,
    '🟢 Ready' AS status,
    'PASS' AS status_code,
    'Modern Google Tag deployed and ready for First-Party Mode' AS details,
    'Deploy Google Tag Gateway / First-Party Mode container to protect measurement' AS steps_to_fix,
    'https://developers.google.com/tag-platform/tag-manager/gateway/setup-guide' AS steps_to_fix_url
  ),

  -- OmniTech Solutions (Needs Upgrade / Partial)
  STRUCT(
    'adv_8802' AS advertiser_id,
    'OmniTech Solutions' AS account_name,
    'partner_9901' AS partner_id,
    CURRENT_DATE() AS audit_date,
    1 AS check_order,
    'YouTube Enabled' AS required_check,
    '❌ Action Required' AS status,
    'FAIL' AS status_code,
    '0 of 2 activities enabled' AS details,
    'Set up conversion tracking for YouTube using YouTube-enabled Floodlight activities' AS steps_to_fix,
    'https://support.google.com/displayvideo/answer/12123563' AS steps_to_fix_url
  ),
  STRUCT(
    'adv_8802' AS advertiser_id,
    'OmniTech Solutions' AS account_name,
    'partner_9901' AS partner_id,
    CURRENT_DATE() AS audit_date,
    2 AS check_order,
    'Dynamic Tagging' AS required_check,
    '🟡 Partial' AS status,
    'WARN' AS status_code,
    '1 of 2 dynamic tags' AS details,
    'Enable dynamic tagging in Floodlight group / configuration' AS steps_to_fix,
    'https://support.google.com/campaignmanager/answer/2823194' AS steps_to_fix_url
  ),
  STRUCT(
    'adv_8802' AS advertiser_id,
    'OmniTech Solutions' AS account_name,
    'partner_9901' AS partner_id,
    CURRENT_DATE() AS audit_date,
    3 AS check_order,
    'Enhanced Conversions' AS required_check,
    '❌ Action Required' AS status,
    'FAIL' AS status_code,
    '0 of 2 activities with EC' AS details,
    'Enable Enhanced Conversions for Floodlight at advertiser & activity levels' AS steps_to_fix,
    'https://support.google.com/campaignmanager/answer/14217426' AS steps_to_fix_url
  ),
  STRUCT(
    'adv_8802' AS advertiser_id,
    'OmniTech Solutions' AS account_name,
    'partner_9901' AS partner_id,
    CURRENT_DATE() AS audit_date,
    4 AS check_order,
    'Data Driven Attribution (DDA)' AS required_check,
    '🟡 Last Interaction' AS status,
    'WARN' AS status_code,
    'Line items using standard / last-click attribution' AS details,
    'Create DDA model in CM360 and apply to DV360 line items' AS steps_to_fix,
    'https://support.google.com/campaignmanager/answer/6361280' AS steps_to_fix_url
  ),
  STRUCT(
    'adv_8802' AS advertiser_id,
    'OmniTech Solutions' AS account_name,
    'partner_9901' AS partner_id,
    CURRENT_DATE() AS audit_date,
    5 AS check_order,
    'Google Tag Gateway (GTG) Readiness' AS required_check,
    '🔴 Needs Upgrade' AS status,
    'FAIL' AS status_code,
    'Legacy tag detected; migrate to modern Google Tag container' AS details,
    'Deploy Google Tag Gateway / First-Party Mode container to protect measurement' AS steps_to_fix,
    'https://developers.google.com/tag-platform/tag-manager/gateway/setup-guide' AS steps_to_fix_url
  ),

  -- Starlight Media (Needs Setup / Not Configured)
  STRUCT(
    'adv_8803' AS advertiser_id,
    'Starlight Media' AS account_name,
    'partner_9901' AS partner_id,
    CURRENT_DATE() AS audit_date,
    1 AS check_order,
    'YouTube Enabled' AS required_check,
    '❌ Action Required' AS status,
    'FAIL' AS status_code,
    '0 of 2 activities enabled' AS details,
    'Set up conversion tracking for YouTube using YouTube-enabled Floodlight activities' AS steps_to_fix,
    'https://support.google.com/displayvideo/answer/12123563' AS steps_to_fix_url
  ),
  STRUCT(
    'adv_8803' AS advertiser_id,
    'Starlight Media' AS account_name,
    'partner_9901' AS partner_id,
    CURRENT_DATE() AS audit_date,
    2 AS check_order,
    'Dynamic Tagging' AS required_check,
    '🟡 Partial' AS status,
    'WARN' AS status_code,
    '1 of 2 dynamic tags' AS details,
    'Enable dynamic tagging in Floodlight group / configuration' AS steps_to_fix,
    'https://support.google.com/campaignmanager/answer/2823194' AS steps_to_fix_url
  ),
  STRUCT(
    'adv_8803' AS advertiser_id,
    'Starlight Media' AS account_name,
    'partner_9901' AS partner_id,
    CURRENT_DATE() AS audit_date,
    3 AS check_order,
    'Enhanced Conversions' AS required_check,
    '❌ Action Required' AS status,
    'FAIL' AS status_code,
    '0 of 2 activities with EC' AS details,
    'Enable Enhanced Conversions for Floodlight at advertiser & activity levels' AS steps_to_fix,
    'https://support.google.com/campaignmanager/answer/14217426' AS steps_to_fix_url
  ),
  STRUCT(
    'adv_8803' AS advertiser_id,
    'Starlight Media' AS account_name,
    'partner_9901' AS partner_id,
    CURRENT_DATE() AS audit_date,
    4 AS check_order,
    'Data Driven Attribution (DDA)' AS required_check,
    '🟡 Last Interaction' AS status,
    'WARN' AS status_code,
    'Line items using standard / last-click attribution' AS details,
    'Create DDA model in CM360 and apply to DV360 line items' AS steps_to_fix,
    'https://support.google.com/campaignmanager/answer/6361280' AS steps_to_fix_url
  ),
  STRUCT(
    'adv_8803' AS advertiser_id,
    'Starlight Media' AS account_name,
    'partner_9901' AS partner_id,
    CURRENT_DATE() AS audit_date,
    5 AS check_order,
    'Google Tag Gateway (GTG) Readiness' AS required_check,
    '🔴 Needs Upgrade' AS status,
    'FAIL' AS status_code,
    'Legacy tag detected; migrate to modern Google Tag container' AS details,
    'Deploy Google Tag Gateway / First-Party Mode container to protect measurement' AS steps_to_fix,
    'https://developers.google.com/tag-platform/tag-manager/gateway/setup-guide' AS steps_to_fix_url
  )
]);
